builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
    main: cmd/gke_versions/main.go
    ldflags:
      - -w -s -X github.com/fregdee/gke_versions.version={{ .Version }}
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: fregdee
    name: gke_versions
